FROM maven:3-alpine
LABEL maintainer="mike@nesets.com"

RUN apk update && \
    apk add \
    python3 \
    python3-dev \
    py3-pip \
    git \
    libffi-dev \
    openssl-dev \
    #linux-headers \
    musl-dev \
    gcc \
    make \
    && pip3 install --upgrade pip setuptools wheel

RUN pip3 --no-cache-dir install --upgrade awscli

RUN pip3 --no-cache-dir install awsebcli --upgrade --user 