FROM maven:3-alpine
LABEL maintainer="mike@nesets.com"

RUN apk update && \
    apk add \
    python3 \
    py3-pip \
    && pip3 install --upgrade pip 
    
RUN pip3 --no-cache-dir install --upgrade awscli
